import React from "react";
import { Link } from "react-router-dom";
// all the content of the page will not diplay at the same time after
// need to change state when use chooses and plan
const MyPlan = () => {
	return (
		<div className="container">
			<h2>Welcome autogenerated name lets set up this Budge plan</h2>
			<div className="idk">
				<h2>What do you have in mind when setting a target</h2>
				<select className="selectPlan" id="selectPlan">
					<option selected>Choose...</option>

					<option value="a href=https://www.w3schools.com ">travel</option>

					<option value="2">Debt Relief</option>
					<option value="3">Grow My Savings</option>
					<option value="4">Date Night</option>
					<option value="5">
						{/*prints out ello onload*/}
						Are chose to customize your own
					</option>
				</select>
			</div>
			<div className="Balance">
				<div>
					<h1>Great Job </h1>
					<h4>Here is what we need to know to get you started</h4>
				</div>
				<div className="inputFields">
					<label>How much debt do you have</label>
					<input id="debt" type="number" placeholder="How much debt do you have" />
					{/*some sort of mapping fucntion where the user can input
                    mulitpule expenses list each one and have total displayed at the
                    end which willl be stored and subtracted from income*/}
					<label>let add up you expenses</label>
					<input id="expenses" type="number" placeholder="let add up you expenses" />
					<label>what is your monthly income</label> <input id="income" type="number" />
					{/*need to store the values of each input */}
				</div>
			</div>
		</div>
	);
};

export default MyPlan;
